image: node:18

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - backend/node_modules/

before_script:
  - cd backend
  - echo "Checking files in backend directory..."
  - ls
  - if ($IsWindows) {
      Write-Host "Running on Windows";
      Remove-Item -Recurse -Force node_modules, package-lock.json -ErrorAction SilentlyContinue
    } else {
      echo "Running on Linux/macOS";
      rm -rf node_modules package-lock.json
    }
  - npm install

install:
  stage: install
  script:
    - echo "Installation completed"

test-backend:
  stage: test
  script:
    - npm run test
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - main