image: node:18

stages:
  - install
  - test
  - deploy

cache:
  key: "node_modules"
  paths:
    - backend/node_modules/

before_script:
  - cd backend
  - npm cache clean --force
  - 'if [ "$OSTYPE" = "msys" ]; then Remove-Item -Recurse -Force node_modules, package-lock.json; else rm -rf node_modules package-lock.json; fi'
  - npm install

test-backend:
  stage: test
  tags:
    - siska
  script:
    - npm run test

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to production..."