image: node:18

stages:
  - install
  - test
  - deploy

cache:
  paths:
    - backend/node_modules/
    - key: ${CI_COMMIT_REF_SLUG}

before_script:
  - cd backend
  - npm cache clean --force
  - rm -rf node_modules package-lock.json
  - npm install

test-backend:
  stage: test
  tags:
    - siska
  script:
    - npm run test

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying to production..."